name = "Qiyao Pan"
license = "CC-BY-4.0"
licenselink = "https://github.com/hugo-apero/hugo-apero/blob/master/LICENSE.md"
description = "Hugo Apero."
homepage = "https://hugo-apero.netlify.app"
tags = ["blog", "personal", "portfolio", "responsive", "customizable"]
features = ["blog", "projects", "talks", "events", "collections", "contact form"]
min_version = "0.79.0"

# If the theme has a single author
[author]
    name = " "
    homepage = " "

# If porting an existing theme
[original]
    author = " "
    homepage = " "
    repo = " "